### ISSUE TITLE
Visualizing Urban Documents on a Map with Type Icons and Stakeholder Colors

### ISSUE THREAD

**Issue by pex9** [SE2-Team-3/polito-se2-24-03-kiruna-explorer#38]
Display urban documents on a map, with an icon representing each document to indicate its type. Additionally, the stakeholder for each document should be distinguishable by the color specified in the documentation.

**Comment by wolf1128** [comment]
Dear Davide,
I'll make sure this UI related suggestions will be delivered to our team.
I appreciate it.
Regards.
